services:
  oracle-db:
    image: gvenzl/oracle-free
    container_name: oracle-db
    ports:
      - "1521:1521"  # Oracle listener
      - "8080:8080"  # SQL Developer Web
    environment:
      ORACLE_PASSWORD: 123
      APP_USER: user
      APP_USER_PASSWORD: 123
    volumes:
      - oracle-data:/opt/oracle/oradata
    restart: unless-stopped

volumes:
  oracle-data:
