services:
  mysql:
    image: mysql:8.4.5
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql 
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "8000:80"
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql-data:
